#!/bin/bash

ttyname=$(tty | tr '/' '_')
base=${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}/$UID}
[[ ! -d $base ]] && mkdir -p "$base"
logfile="$base/.agg.log.$ttyname"
tmpfile="$base/.agg.tmp.$$"

pwd -L > "$tmpfile"
echo "$@" >> "$tmpfile"
ag -s --column --nogroup --color "$@" | cat -n | tee -ai "$tmpfile" | ${PAGER:-less -FRXM}
if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
  mv "$tmpfile" "$logfile"
else
  exit "${PIPESTATUS[0]}"
fi
